name: Docker Image CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Testing
        run: pwd

      - name: Testin2
        run: ls -hal
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: snekone/nym-mixnode-docker:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
